### ISSUE TITLE
feat: Support third party completion 

### ISSUE THREAD

**Issue by ShalokShalom** [Rosettea/Hilbish#262]
Some shells, like nushell, [support the completion of other shells](https://www.nushell.sh/cookbook/external_completers.html#fish-completer), like fish. 

I currently use fish, and one of the remaining issues I have with Hilbish, is the proper support of such completions. 

The fish completer in particularly has the most comprehensive suite of completions, so I would support that one specifically.

**Comment by TorchedSammy** [comment]
it looks like this just calls fish for completions? you can do that in your own user config [via this here](https://rosettea.github.io/Hilbish/docs/api/hilbish/hilbish.completions/#handlerline-pos).
i would rather add support for manpages, since that's what fish does.

docs are kinda lacking, so if you need anything else just ask. (im working on it)

**Comment by ShalokShalom** [comment]
Yes, this does just call fish for completion. So, we already have the basic functionality to implement this, and it seems like we are lacking someone to implement this based on top of it.

Thanks a lot

**Comment by TorchedSammy** [comment]
i'll work on adding completions for builtin commands soon, and i'll also write a plugin to support carapace completions at least. that'll be in a next release though.
