### ISSUE TITLE
Confusing documentation

### ISSUE THREAD

**Issue by CapedBojji** [Rosettea/Hilbish#270]
is it possible to just show pictures of code instead of confusing explanations. The completion documentation makes no sense to me, if i want to enable custom completions, do i use the handler function or do i use the other 3 what is the purpose of the other 3. A simple image of the code and what it produces is all is needed
<img width="590" alt="image" src="https://github.com/Rosettea/Hilbish/assets/115787932/b0298d64-811a-4a9d-a01a-f415570db025">
look at how simple nushell does it. thats all it takes to understand how it works

**Comment by TorchedSammy** [comment]
i'm working on improving the docs in #260 but i've also been doing other things irl.

to make completions for a command, here's an example:
```lua
hilbish.complete('animal', function(query, ctx, fields)
	local comp = {
		{
			items = {'dog', 'cat'},
			type = 'grid'
		}
	}

	return comp, query
end)
```

this is the bare minimum. it turns comp and the prefix, so you'll have to cut your completion string for it to work properly. if you have any suggestions on how to improve the docs that would be great, since the "confusing explanation" is still needed.
